#!/bin/sh
# vim: ts=4:et:sts=4
# $Id: beanstalkd.postrm 89 2009-01-03 16:34:01Z robert $

set -e

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d beanstalkd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask beanstalkd.socket >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		export _DEB_SYSTEMD_HELPER_PURGE=1
		deb-systemd-helper disable beanstalkd.socket >/dev/null
		deb-systemd-helper unmask beanstalkd.socket >/dev/null
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask beanstalkd.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		export _DEB_SYSTEMD_HELPER_PURGE=1
		deb-systemd-helper disable beanstalkd.service >/dev/null
		deb-systemd-helper unmask beanstalkd.service >/dev/null
	fi
fi
# End automatically added section


PACKAGE=beanstalkd
DEFAULTSFILE=/etc/default/$PACKAGE


case "$1" in
   failed-install|abort-install|abort-upgrade|failed-upgrade)
        exit 0
    ;;

    remove)
        if [ -d /var/lib/beanstalkd ]; then
            if [ $(find /var/lib/beanstalkd | wc -l) -eq 1 ]; then
                rmdir /var/lib/beanstalkd
            fi
        fi
        exit 0
    ;;
    purge)
        echo "purge requested, thus removing /var/lib/beanstalkd"
        rm -rf /var/lib/beanstalkd/

        # remove user, group and home directory beanstalkd
        deluser --remove-home beanstalkd >/dev/null 2>&1 || true

        exit 0
    ;;
    upgrade|disappear)
        exit 0
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
