#!/bin/sh

set -e


PACKAGE=beanstalkd
DEFAULTSFILE=/etc/default/$PACKAGE

case "$1" in
    configure)

        # Create beanstalkd system user
        getent passwd beanstalkd > /dev/null || \
            adduser --quiet --system --home /var/lib/beanstalkd  --no-create-home \
            --gecos 'Beanstalk Server' --group beanstalkd

        ;;

    failed-upgrade|abort-upgrade|abort-remove|abort-deconfigure|in-favour|removing)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 1;
        ;;
esac

chown beanstalkd:beanstalkd /var/lib/beanstalkd/

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask beanstalkd.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled beanstalkd.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable beanstalkd.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state beanstalkd.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if deb-systemd-helper debian-installed beanstalkd.socket; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask beanstalkd.socket >/dev/null || true

	if deb-systemd-helper --quiet was-enabled beanstalkd.socket; then
		# Create new symlinks, if any.
		deb-systemd-helper enable beanstalkd.socket >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state beanstalkd.socket >/dev/null || true
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/beanstalkd" ] || [ -e "/etc/init/beanstalkd.conf" ]; then
	if [ ! -e "/etc/init/beanstalkd.conf" ]; then
		update-rc.d beanstalkd defaults >/dev/null
	fi
	if [ -n "$2" ]; then
		_dh_action=restart
	else
		_dh_action=start
	fi
	invoke-rc.d beanstalkd $_dh_action || exit $?
fi
# End automatically added section


exit 0
