#!/bin/sh
set -e
# Automatically added by dh_installinit
if ([ -x "/etc/init.d/beanstalkd" ] || [ -e "/etc/init/beanstalkd.conf" ]) && \
   [ "$1" = remove ]; then
	invoke-rc.d beanstalkd stop || exit $?
fi
# End automatically added section
